### ISSUE TITLE
How to find neighbors

### ISSUE THREAD

**Issue by azmeuk** [aaliddell/s2cell#1]
Hi. Thank you for your work in this library. I have a feature request:

Given a reference point, and a heterogeneous set of points, one might want to search some points in the set based on the distance with the reference point. In the geohash world this is [usually done by computing the 8 neighbor cells](https://gis.stackexchange.com/questions/18330/using-geohash-for-proximity-searches).

A [ticket at s2geometry](https://github.com/google/s2geometry/issues/80) suggest to build a [S2PointIndex](http://s2geometry.io/devguide/cpp/quickstart#s2pointindex) and querying it with a [S2ClosestPointQuery](http://s2geometry.io/devguide/cpp/quickstart#s2closestpointquery) (in the cpp implementation). It seems those datastructures are not present in this library, and this is fine, since I would prefer to use my own datastructures (or at least the one my database library allow me to use).

**I suggest implementing a method that, given a cell and a precision, returns all the neighbor cells.**

This would allow me to implement the algorithm described in [this SO answer](https://gis.stackexchange.com/a/92331/145500).

It is possible that there are some concepts about S2 that I do not really get though. In this case maybe a word about this in the documentation would be welcome?

What do you think?

**Comment by aaliddell** [comment]
Hi, I hadn't looked much at adding neighbour functions yet, since they're outside of the core conversions. However, I think I have the necessary primitive functions to do it though, since it happens in the IJ coord space IIRC.

If you want a direct mapping of the C++ implementation classes into Python though, you may be better off with the s2geometry built-in python module or s2sphere.

**Comment by aaliddell** [comment]
See #16
